### ISSUE TITLE
Screenshot broken on 1.1.7

### ISSUE THREAD

**Issue by dabaicaifen** [crowdin/mobile-sdk-ios#110]
After upgrading Crowdin to 1.1.7, I found the screenshot function is broken.
And after some debugging, I found several issues.

# Precondition: 
My project has multiple localized string files.

# Issues
## 1. Distribution only contains 1 file:
- This download `[CrowdinMappingDownloader download(with hash:...]`  succeed.
- But `[ScreenshotUploader uploadScreenshot(screenshot:...]` gets early return. Because it hits line 75 in `ScreenshotUploader`(Newly added in 1.1.7) since the string files do not exist.
- The screenshot function is only working on the specific screen (the file contains in the distribution)
## 2, Distribution contains multiple files, such as a folder
- This download `[CrowdinMappingDownloader download(with hash:...]`  returns an error.

**Comment by crowdin-support** [comment]
Hello,

Thank you for reaching Crowdin team.

Kindly note that our replies may be slower than usual due to national
holidays until January 8th (response time should not exceed 24h though),
also live chat will become active again from January 8th, 5AM UTC.

Any urgent inquiries will be resolved with the highest priority, inbox is
always monitored 🙄

All the best in 2021!

--
Sincerely yours,
Crowdin Team
{#HS:1389745201-138516#}

**Comment by Andrulko** [comment]
Thanks a lot for a detailed report! We'll make sure this case is prioritized and gets resolved shortly

**Comment by crowdin-support** [comment]
Hello,

Thank you for reaching Crowdin team.

Kindly note that our replies may be slower than usual due to national
holidays until January 8th (response time should not exceed 24h though),
also live chat will become active again from January 8th, 5AM UTC.

Any urgent inquiries will be resolved with the highest priority, inbox is
always monitored 🙄

All the best in 2021!

--
Sincerely yours,
Crowdin Team
{#HS:1389749150-138517#}

**Comment by serhii-londar** [comment]
@dabaicaifen Could you please try out the new version 1.1.8, screenshots should be fixed there. Please check and give your feedback.

**Comment by dabaicaifen** [comment]
@serhii-londar The screenshots function is still broken, and I still hit the same error that I reported.

**Comment by andrii-bodnar** [comment]
Hi @dabaicaifen!

We can't reproduce this error. Could you please provide more details about your environment, SDK configuration? 

Is this error is reproducible on the Example project?

**Comment by dabaicaifen** [comment]
The issue is occurring on an Enterprise product, which contains a very large amount of the localized files (47 localized files, and a specific folder for localization).
I think the issue is related to your distribution link cannot handle this size of the localized files. Your example project might be too small for this issue.

# Configuration:

`providerConfig`: distribution hash string and source language ("en").
`loginConfig`: client id, client secret, scope("project.screenshot"), redirectURI("crowdintest://").

```
let crowdinSDKConfig = CrowdinSDKConfig.config()
    .with(crowdinProviderConfig: providerConfig)
    .with(screenshotsEnabled: true)
    .with(loginConfig: loginConfig)
    .with(settingEnabled: true)
```

# Environment:
Xcode 12.3
iPhone 12 simulator
iOS 14.3
CrowdinSDK: 1.1.8

**Comment by serhii-londar** [comment]
@dabaicaifen Could you please check whether this issue fixed in v. 1.2.0?

**Comment by andrii-bodnar** [comment]
@dabaicaifen Could you please check if this issue is fixed now for you?
