### ISSUE TITLE
Auto-tagging not working

### ISSUE THREAD

**Issue by dabaicaifen** [crowdin/mobile-sdk-ios#111]
**Describe the bug**
The uploaded screenshots without tagging.

**To Reproduce**
1, Only 1 localized string file, and related screen.
2, Integrate SDK, and capture screenshots.

**Expected behavior**
The uploaded screenshots have auto-tagging.

**Smartphone (please complete the following information):**
 - Device: simulator, iPhone 12
 - OS: iOS 14.3
 - Crowdin: 1.1.7

**Additional context**
After debugging the code, the error returns at line 101 in `ScreenshotUploader.swift`, from `screenshotsAPI.createScreenshotTags(projectId:...`
The error is:
```
▿ DecodingError
  ▿ keyNotFound : 2 elements
    - .0 : CodingKeys(stringValue: "data", intValue: nil)
    ▿ .1 : Context
      - codingPath : 0 elements
      - debugDescription : "No value associated with key CodingKeys(stringValue: \"data\", intValue: nil) (\"data\")."
      - underlyingError : nil
```

**Comment by DimaYashchyshyn** [comment]
Hi @dabaicaifen 

Thanks for informing us! Already passed it into further investigation

**Comment by serhii-londar** [comment]
@dabaicaifen Could you please try out the new version 1.1.8, screenshots should be fixed there. Please check and give your feedback.

**Comment by dabaicaifen** [comment]
@serhii-londar Auto-tagging is still broken because the screenshots function is still broken (https://github.com/crowdin/mobile-sdk-ios/issues/110)

**Comment by serhii-londar** [comment]
@dabaicaifen Could you please check whether this issue fixed in v. 1.2.0?

**Comment by andrii-bodnar** [comment]
@dabaicaifen Could you please check if this issue is fixed now for you?
